[[teaching_experience]]
period = "October 2024 - January 2025"
role = "Teacher"
institution = "Université Grenoble Alpes"
course = "Advanced Methods of Operations Research"
program = "Master's of Operations Research, Combinatorics, and Optimization"
details = "Bender's decomposition, convex optimization formulation, methods, and applications"
hours = 20
